### ISSUE TITLE
installation instructions not fool-proof

### ISSUE THREAD

**Issue by sneumann** [althonos/mzml2isa#18]
Hi, 
I am following the instructions at 
http://2isa.readthedocs.io/en/latest/mzml2isa/install.html

but the instructions on https://github.com/ISA-tools/mzml2isa/blob/master/README.rst
`mzml2isa -i /path/to/mzml_files/ -o /path/to/out_folder/ -s name_of_study`
don't work because there is no `mzml2isa` executable. But I am not 
python wizard enough to figure out myself. 
Yours, Steffen

**Comment by sneumann** [comment]
Hm, there is something in https://github.com/Tomnl/mzml2isa/blob/master/scripts/mzml2isa_parser.py
but I could imagine that is outdated ?!

**Comment by Tomnl** [comment]
Hi Steffen,

Yes my original repo is outdated now. Rather than update my code, I think to avoid any confusion I will contact github to remove the fork to my old mzml2isa repo. I will then make my old repo private so we just have Martin's (althonos) repo as the main development area. What do you think @althonos?

Regarding the executable: It is strange that it didn't work straight away (the setup.py file should automatically do this [line 47-50](https://github.com/althonos/mzml2isa/blob/master/setup.py)) 

However, you can run the parsing script directly from the package code using the python script ['parsing.py'](https://github.com/althonos/mzml2isa/blob/master/mzml2isa/parsing.py) (used to be called mzml2isa_parser.py)

``/path/to/mzml2isa/parsing.py -i /path/to/mzml_files/ -o /path/to/out_folder/ -s name_of_study``

What OS and python version were you using? And how did you install?

**Comment by sneumann** [comment]
Hi, I installed mzml2isa-0.4.28 via pip to $HOME.
Maybe I need a $HOME/bin for this to work. 
Your commandline above worked nicely, though. 
Thanks, Steffen

**Comment by sneumann** [comment]
P.S.: I found the executable in $HOME/.local/bin/

**Comment by rsalek** [comment]
Thank you for having a look @sneumann

**Comment by althonos** [comment]
Hi Steffen,

Did you install mzml2isa with pip or by cloning the git repository ?

Try running the following command if the mzml2isa executable was not
installed (although it should be if you ran the setup.py or the pip
install) : `python -m mzml2isa.parsing -i /your/mzml/dir -o
/your/output/dir -s STUDYID`

Just to know, what OS are you running it on ?

Let me know if this still doesn't work.

Best regards,
Martin.

**Comment by sneumann** [comment]
Hi, I installed via `pip -v install --upgrade mzml2isa --user # install only for the current user, no rights needed`, on an Ubuntu 16.04. As mentioned above, I found the executable in the end. Thanks for 
coming back. Yours, Steffen

**Comment by althonos** [comment]
Hi Steffen,
yes using the `--user` flag with pip will install everything under
~/.local/bin, which is in the $PATH most of the time, but i'll add a
warning about that in the documentation.
